openapi: 3.0.1
info:
  title: Venue Finder
  version: 1.0.0
  description: Search NYC nightlife venues by music, type, bottle service, and date using The Host’s recommendation engine.
servers:
  - url: https://askthehost-customgpt-plugin.onrender.com

paths:
  /venues/search:
    get:
      operationId: searchVenues
      summary: Search venues by music preference, venue type, bottle service, and date
      parameters:
        - name: music_preference
          in: query
          required: false
          schema:
            type: string
            enum: [house, hip hop, pop]
          description: Preferred music genre
        - name: venue_type
          in: query
          required: false
          schema:
            type: string
            enum: [bar, lounge, club, rooftop]
          description: Type of venue
        - name: bottle_service
          in: query
          required: false
          schema:
            type: boolean
          description: Whether bottle service is desired
        - name: date_requested
          in: query
          required: false
          schema:
            type: string
            enum: [Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday]
          description: Day of the week for the night out
      responses:
        '200':
          description: A list of venues matching the search criteria
          content:
            application/json:
              schema:
                type: object
                properties:
                  records:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        fields:
                          type: object
                          additionalProperties: true
