openapi: 3.0.1
info:
  title: Airtable Venue API
  version: 1.0.0
servers:
  - url: https://askthehost-customgpt-plugin.onrender.com
paths:
  /venues:
    get:
      summary: Get all venues
      responses:
        '200':
          description: A list of venues
  /venues/search:
    get:
      summary: Search for venues by name or filter
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: false
        - in: query
          name: min_capacity
          schema:
            type: integer
          required: false
        - in: query
          name: bottle_service
          schema:
            type: boolean
          required: false
      responses:
        '200':
          description: Filtered venue results
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
